// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXuDpWKhgC16y7BqpSqGsc-FdxrhpZHho',
    appId: '1:123873713539:web:014fb545ed9bac76552ab6',
    messagingSenderId: '123873713539',
    projectId: 'smarte-cloudservice-846b2',
    authDomain: 'smarte-cloudservice-846b2.firebaseapp.com',
    storageBucket: 'smarte-cloudservice-846b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgrZbP93QZbYgEGPwShpdlLK84MU2bsrY',
    appId: '1:123873713539:android:211c8a7596fdf2e7552ab6',
    messagingSenderId: '123873713539',
    projectId: 'smarte-cloudservice-846b2',
    storageBucket: 'smarte-cloudservice-846b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUabvKOhct2ntxoQ08FLzUD2K8F653Ae0',
    appId: '1:123873713539:ios:6b157d46163cc474552ab6',
    messagingSenderId: '123873713539',
    projectId: 'smarte-cloudservice-846b2',
    storageBucket: 'smarte-cloudservice-846b2.appspot.com',
    androidClientId: '123873713539-4cenuvbbi9j7bdku3peada0d1psi9r80.apps.googleusercontent.com',
    iosClientId: '123873713539-lnmc3mh34f7j8u53hvvu8lcb6diar504.apps.googleusercontent.com',
    iosBundleId: 'com.smarte.ios',
  );
  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyAUabvKOhct2ntxoQ08FLzUD2K8F653Ae0',
  //   appId: '1:123873713539:ios:a249e4e9d9407c78552ab6',
  //   messagingSenderId: '123873713539',
  //   projectId: 'smarte-cloudservice-846b2',
  //   storageBucket: 'smarte-cloudservice-846b2.appspot.com',
  //   androidClientId:
  //       '123873713539-4cenuvbbi9j7bdku3peada0d1psi9r80.apps.googleusercontent.com',
  //   iosClientId:
  //       '123873713539-kv33qm7ftp0k2kcdnmvuapmqaq4lfh8g.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.helixAi',
  // );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUabvKOhct2ntxoQ08FLzUD2K8F653Ae0',
    appId: '1:123873713539:ios:a249e4e9d9407c78552ab6',
    messagingSenderId: '123873713539',
    projectId: 'smarte-cloudservice-846b2',
    storageBucket: 'smarte-cloudservice-846b2.appspot.com',
    androidClientId: '123873713539-4cenuvbbi9j7bdku3peada0d1psi9r80.apps.googleusercontent.com',
    iosClientId: '123873713539-kv33qm7ftp0k2kcdnmvuapmqaq4lfh8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.helixAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXuDpWKhgC16y7BqpSqGsc-FdxrhpZHho',
    appId: '1:123873713539:web:335991113d54c62e552ab6',
    messagingSenderId: '123873713539',
    projectId: 'smarte-cloudservice-846b2',
    authDomain: 'smarte-cloudservice-846b2.firebaseapp.com',
    storageBucket: 'smarte-cloudservice-846b2.appspot.com',
  );
}
